# Generated by Django 3.0.8 on 2020-07-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_destination_id', models.IntegerField()),
                ('route', models.CharField(max_length=255)),
                ('url_main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lupi.Posts')),
            ],
        ),
    ]
