# Generated by Django 3.0.8 on 2020-07-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lupi', '0002_remove_routes_ancestors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='main',
        ),
        migrations.AddField(
            model_name='routes',
            name='main_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destination_id',
            field=models.IntegerField(default=0),
        ),
    ]
