# Generated by Django 3.0.8 on 2020-07-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lupi', '0002_auto_20200718_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='route',
            new_name='ancestors',
        ),
    ]
