# Generated by Django 3.0.8 on 2020-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lupi', '0003_auto_20200720_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
